[versions]
coroutines = "1.7.3"
graalvm = "0.10.1"
injectTestResources = "0.3.3"
klogging = "3.0.5"
koin = "3.5.3"
koinKsp = "1.3.1"
konform = "0.4.0"
kotest = "5.8.0"
kotlin = "1.9.22"
kotlinter = "4.2.0"
ksp = "1.9.22-1.0.17"
ktor = "2.3.8"
logback = "1.4.14"
mockk = "1.13.9"
mongodb = "4.10.1"
openapiGenerator = "7.3.0"
prometeus = "1.6.3"
testcontainers = "1.19.7"
