openapi: 3.1.0
info:
  title: Whats the loss API
  version: 0.0.1

# @todo add notion of users

paths:
  /logging/run:
    post:
      summary: "Add a run"
      requestBody:
        content:
          application/protobuf:
            schema:
              $ref: '#/components/schemas/RunProperties'
      responses:
        200:
          content:
            application/protobuf:
              schema:
                $ref: '#/components/schemas/RunId'
    put:
      summary: "Update a run (its status and configuration)"
      parameters:
        - name: run_id
          in: path
          schema:
            $ref: "#/components/schemas/RunId"
      requestBody:
        content:
          application/protobuf:
            schema:
              properties:
                run_status:
                  type: string
                  enum: [ running, crashed, canceled, finished ]
                configuration:
                  type: object
                  title: "A json object of configuration values"

  /logging/run/logSchema:
    put:
      parameters:
        - name: run_id
          in: path
          schema:
            $ref: "#/components/schemas/RunId"
      summary: "Update the log schema of a run. This includes the datatypes of logged values and their types."
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RunLogSchema'

  /logging/logValues:
    post:
      summary: "Add a new log entry of values, optionally linked to a step value"
      parameters:
        - name: run_id
          in: path
          schema:
            $ref: "#/components/schemas/RunId"
      requestBody:
        content:
          application/protobuf:
            schema:
              allOf:
                - $ref: '#/components/schemas/LoggedValues_Full'
                - $ref: '#/components/schemas/RunId'
  /logging/logMedia:
    post:
      summary: "Log a media object (image, video), optionally linked to a step value"
      parameters:
        - name: run_id
          in: path
          schema:
            $ref: "#/components/schemas/RunId"
        - name: key_flattened
          in: query
          schema:
            type: string
      requestBody:
        content:
          image/*:
            schema:
              type: string
              format: binary
          video/*:
            schema:
              type: string
              format: binary
components:
  schemas:
    RunProperties:
      properties:
        project:
          type: string
        experiment:
          type: string
        group:
          type: array
          items:
            type: string
        name:
          type: string
        configuration:
          type: object
          title: "A json object of configuration values"
    RunId:
      properties:
        run_id:
          type: string
          format: uuid

    RunLogSchema:
      properties:
        loggedValues:
          type: array
          items:
            properties:
              key_flattened:
                type: string
              datatype:
                type: string
                description: "the actual value data type of the logged data for this key."
                enum: [ scalar, vector, image, video, dataframe ]
              assigned_type_name:
                type: string
                description: "links to a user defined type by its name. Note this is like a decorator and not related to the actual datatype of the logged value."
        types:
          type: array
          description: "A user defined type describing what value is 'optimal' for linked logged value keys."
          items:
            properties:
              name:
                type: string
              optimal:
                type: string
                description: "Is it good/better for a value to be high or low"
                enum: [ high, low ]
              unit:
                type: string
                examples: ['m/s', 'seconds']
        metrics:
          type: array
          description: "A list of logged value key that allow to determine how good a run is."
          items:
            properties:
              key_flattened:
                type: string
                description: "They key of the logged value"
              optimal:
                type: string
                description: "Is it good/better for a value to be high or low. This can also be inherited to the type assigned to a logged value key."
                enum: [ high, low ]




    # this is just to show how the structure of logged values.
    # for network transfer a compressed version (e.g. no keys) will be used.
    LoggedValues_Full:
      properties:
        values:
          type: array
          items:
            $ref: '#/components/schemas/LoggedValues_Full_Value'
        step:
          type: integer
        timestamp:
          type: string
          format: date-time

    LoggedValues_Full_Value:
      properties:
        key_flattened:
          type: string
        value:
          type:
            - array
            - number

