name: Test core component

on:
  push:
    paths:
      - 'core/**'
      - 'docs/api/openapi.yaml'
      - '.github/workflows/gradle.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'
      - uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Execute Gradle build
        run: ./gradlew check
        working-directory: core
