name: Test core component

on:
  push:
    paths:
      - 'core/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: core
      - name: Execute Gradle build
        run: ./gradlew check
        working-directory: core
