name: Generate and Publish API docs

on:
  push:
    paths:
      - 'docs/api/openapi.yaml'

jobs:
  publish_api_to_gh_pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: redocly cli bundle
        uses: fluximus-prime/redocly-cli-github-action@v1
        with:
          args: 'build-docs docs/api/openapi.yaml --output docs/api/index.html'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/api
          publish_branch: gh-pages
